# Generated by Django 4.1 on 2022-08-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='dialog_output',
            field=models.TextField(max_length=1500),
        ),
    ]
