# Generated by Django 4.1 on 2022-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appuser_email_alter_appuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.AddField(
            model_name='appuser',
            name='dungeon',
            field=models.JSONField(default=''),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
