# Generated by Django 4.1 on 2022-08-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_appuser_dungeon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='dialog_output',
            new_name='dialog',
        ),
        migrations.RenameField(
            model_name='dialog',
            old_name='description',
            new_name='icon',
        ),
    ]
