# Generated by Django 4.1 on 2022-08-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_dialog_output_dialog_dialog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='dungeon',
        ),
    ]
